/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program.gaji.karyawan;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static program.gaji.karyawan.Database.rst;
import static program.gaji.karyawan.Database.stm;
import java.text.*;

/**
 *
 * @author Luincerz
 */
public class Home_UI extends javax.swing.JFrame {
    Database db = new Database();
    String nama,pendidikan,kelamin,sisa_cuti,tanggal;
    /**
     * Creates new form Home_UI
     */
    public Home_UI() {
//        Database konek = new Database();
        initComponents();
        tampil_tabel();
    }
    
    
//  Menampilkan Tabel Karyawan
    public void tampil_tabel(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Nama");
        tb.addColumn("Pendidikan");
        tb.addColumn("Kelamin");
        tb.addColumn("Sisa Cuti");
        tb.addColumn("Tanggal");
        jTable1.setModel(tb);
        tb.fireTableDataChanged();
      
        try{
            rst=stm.executeQuery("select * from karyawan");
            while (rst.next()){
                tb.addRow(new Object[]{
                rst.getString("nama"),
                rst.getString("pendidikan"),
                rst.getString("kelamin"),
                rst.getString("sisa_cuti"),
                rst.getString("tanggal"),
                });
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_UI.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    
    
    //  Mengambil variabel nama
    public String getNama() {
        return nama = txt_insert_nama.getText();
    }

    public void setNama(String nama) {
        this.nama = nama;
    }
    
//  Mengambil variabel tanggal
    public String getTanggal() {
        return tanggal = txt_insert_tanggal.getText();
    }

    public void setTanggal(String tanggal) {
        this.tanggal = tanggal;
    }
    
//  Mengambil variabel pendidikan berdasarkan radio box
    public String pilih_pendidikan(){
        String pendidikan = null;
        
        if (pend_sma.isSelected() == true){
            pendidikan = "SMA";
        }
        else if (pend_d3.isSelected() == true){
            pendidikan = "D3";
        }
        else if (pend_s1.isSelected() == true){
            pendidikan = "S1";
        }
        return pendidikan;
    }
    
//  Mengambil variabel kelamin berdasrkan radio box 
    public String pilih_kelamin(){
        String kelamin = null;
        
        if (rad_laki_laki.isSelected() == true){
            kelamin = "Laki-laki";         
        }
        else if (rad_perempuan.isSelected() == true){
            kelamin = "Perempuan";          
        }
        return kelamin;
    }
    
//  mengambil variabel sisa cuti berdasarkan pilihan kelamin
    public Integer sisa_cuti(){
        int cuti_sisa = 0;
        
        if ("Laki-laki".equals(this.pilih_kelamin())){
            cuti_sisa = 5;
        }
        else if ("Perempuan".equals(this.pilih_kelamin())){
            cuti_sisa = 30;
        }
        return cuti_sisa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int xx,xy;
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroup_Pendidikan = new javax.swing.ButtonGroup();
        btGroup_Kelamin = new javax.swing.ButtonGroup();
        bg_main = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        but_menu_karyawan = new javax.swing.JPanel();
        label_daftar_karyawan = new javax.swing.JLabel();
        but_menu_gaji = new javax.swing.JPanel();
        label_bayar_gaji = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        main_menu = new javax.swing.JTabbedPane();
        panel_daftar_karyawan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button_delete = new javax.swing.JButton();
        btn_tambah_data_baru = new javax.swing.JToggleButton();
        panel_input_karyawan = new javax.swing.JPanel();
        txt_insert_nama = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pend_sma = new javax.swing.JRadioButton();
        pend_s1 = new javax.swing.JRadioButton();
        pend_d3 = new javax.swing.JRadioButton();
        btn_insert_data = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rad_laki_laki = new javax.swing.JRadioButton();
        rad_perempuan = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txt_insert_tanggal = new javax.swing.JTextField();
        panel_gaji = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cb_pilih_nama = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbox_cuti = new javax.swing.JCheckBox();
        cbox_izin = new javax.swing.JCheckBox();
        cbox_sakit = new javax.swing.JCheckBox();
        cbox_alfa = new javax.swing.JCheckBox();
        txt_cuti = new javax.swing.JTextField();
        txt_izin = new javax.swing.JTextField();
        txt_sakit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_alfa = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        Lembur = new javax.swing.JLabel();
        cbox_lembur = new javax.swing.JCheckBox();
        txt_lembur = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_slip = new javax.swing.JTextArea();
        but_bayar_gaji = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        bg_main.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bg_mainMouseDragged(evt);
            }
        });
        bg_main.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bg_mainFocusLost(evt);
            }
        });
        bg_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(85, 65, 118));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        but_menu_karyawan.setBackground(new java.awt.Color(85, 98, 215));
        but_menu_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                but_menu_karyawanMousePressed(evt);
            }
        });

        label_daftar_karyawan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_daftar_karyawan.setForeground(new java.awt.Color(255, 255, 255));
        label_daftar_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_name_tag_25px.png"))); // NOI18N
        label_daftar_karyawan.setText("Daftar Karyawan");
        label_daftar_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_daftar_karyawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_daftar_karyawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_daftar_karyawanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout but_menu_karyawanLayout = new javax.swing.GroupLayout(but_menu_karyawan);
        but_menu_karyawan.setLayout(but_menu_karyawanLayout);
        but_menu_karyawanLayout.setHorizontalGroup(
            but_menu_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but_menu_karyawanLayout.createSequentialGroup()
                .addComponent(label_daftar_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        but_menu_karyawanLayout.setVerticalGroup(
            but_menu_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but_menu_karyawanLayout.createSequentialGroup()
                .addComponent(label_daftar_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menu.add(but_menu_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 80));

        but_menu_gaji.setBackground(new java.awt.Color(85, 98, 215));
        but_menu_gaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                but_menu_gajiMousePressed(evt);
            }
        });

        label_bayar_gaji.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_bayar_gaji.setForeground(new java.awt.Color(255, 255, 255));
        label_bayar_gaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_rent_25px.png"))); // NOI18N
        label_bayar_gaji.setText("Bayar Gaji");
        label_bayar_gaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_bayar_gajiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_bayar_gajiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_bayar_gajiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout but_menu_gajiLayout = new javax.swing.GroupLayout(but_menu_gaji);
        but_menu_gaji.setLayout(but_menu_gajiLayout);
        but_menu_gajiLayout.setHorizontalGroup(
            but_menu_gajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, but_menu_gajiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_bayar_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        but_menu_gajiLayout.setVerticalGroup(
            but_menu_gajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, but_menu_gajiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_bayar_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu.add(but_menu_gaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 80));

        bg_main.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 770));

        jPanel1.setBackground(new java.awt.Color(122, 72, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(122, 72, 221));
        jPanel7.setLayout(null);
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 139, -1, -1));

        bg_main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -20, 1080, 140));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setAlignmentX(2.0F);
        jTable1.setAlignmentY(2.0F);
        jScrollPane1.setViewportView(jTable1);

        button_delete.setBackground(new java.awt.Color(255, 102, 102));
        button_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button_delete.setForeground(new java.awt.Color(255, 255, 255));
        button_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_minus_25px.png"))); // NOI18N
        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        btn_tambah_data_baru.setBackground(new java.awt.Color(102, 153, 255));
        btn_tambah_data_baru.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_tambah_data_baru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_25px.png"))); // NOI18N
        btn_tambah_data_baru.setText("Tambah Baru");
        btn_tambah_data_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_data_baruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_daftar_karyawanLayout = new javax.swing.GroupLayout(panel_daftar_karyawan);
        panel_daftar_karyawan.setLayout(panel_daftar_karyawanLayout);
        panel_daftar_karyawanLayout.setHorizontalGroup(
            panel_daftar_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_daftar_karyawanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel_daftar_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tambah_data_baru)
                    .addGroup(panel_daftar_karyawanLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_delete)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        panel_daftar_karyawanLayout.setVerticalGroup(
            panel_daftar_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_daftar_karyawanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_daftar_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_daftar_karyawanLayout.createSequentialGroup()
                        .addComponent(btn_tambah_data_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_delete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50))
        );

        main_menu.addTab("tab1", panel_daftar_karyawan);

        txt_insert_nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Pendidikan Terakhir");

        pend_sma.setBackground(new java.awt.Color(204, 204, 204));
        btGroup_Pendidikan.add(pend_sma);
        pend_sma.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        pend_sma.setText("SMA");

        pend_s1.setBackground(new java.awt.Color(204, 204, 204));
        btGroup_Pendidikan.add(pend_s1);
        pend_s1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        pend_s1.setText("S1");

        pend_d3.setBackground(new java.awt.Color(204, 204, 204));
        btGroup_Pendidikan.add(pend_d3);
        pend_d3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        pend_d3.setText("D3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pend_s1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pend_sma, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pend_d3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pend_sma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pend_d3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pend_s1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btn_insert_data.setBackground(new java.awt.Color(102, 153, 255));
        btn_insert_data.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_insert_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_25px.png"))); // NOI18N
        btn_insert_data.setText("Simpan");
        btn_insert_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insert_dataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Nama");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Jenis Kelamin");

        rad_laki_laki.setBackground(new java.awt.Color(204, 204, 204));
        btGroup_Kelamin.add(rad_laki_laki);
        rad_laki_laki.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        rad_laki_laki.setText("Laki-Laki");

        rad_perempuan.setBackground(new java.awt.Color(204, 204, 204));
        btGroup_Kelamin.add(rad_perempuan);
        rad_perempuan.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        rad_perempuan.setText("Perempuan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rad_laki_laki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rad_perempuan, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_laki_laki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_perempuan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Tanggal");

        txt_insert_tanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel_input_karyawanLayout = new javax.swing.GroupLayout(panel_input_karyawan);
        panel_input_karyawan.setLayout(panel_input_karyawanLayout);
        panel_input_karyawanLayout.setHorizontalGroup(
            panel_input_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_input_karyawanLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panel_input_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_input_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_input_karyawanLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_insert_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_input_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_insert_data)
                        .addGroup(panel_input_karyawanLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_insert_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(721, Short.MAX_VALUE))
        );
        panel_input_karyawanLayout.setVerticalGroup(
            panel_input_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_input_karyawanLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel_input_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_insert_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_input_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_insert_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_insert_data, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        main_menu.addTab("tab2", panel_input_karyawan);

        cb_pilih_nama.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        cb_pilih_nama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "www" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Nama");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Izin / Cuti");

        cbox_cuti.setBackground(new java.awt.Color(204, 204, 204));
        cbox_cuti.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbox_cuti.setText("Cuti");
        cbox_cuti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_cutiItemStateChanged(evt);
            }
        });

        cbox_izin.setBackground(new java.awt.Color(204, 204, 204));
        cbox_izin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbox_izin.setText("Izin");
        cbox_izin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_izinItemStateChanged(evt);
            }
        });

        cbox_sakit.setBackground(new java.awt.Color(204, 204, 204));
        cbox_sakit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbox_sakit.setText("Sakit");
        cbox_sakit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_sakitItemStateChanged(evt);
            }
        });

        cbox_alfa.setBackground(new java.awt.Color(204, 204, 204));
        cbox_alfa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbox_alfa.setText("Alfa");
        cbox_alfa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_alfaItemStateChanged(evt);
            }
        });

        txt_cuti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cuti.setEnabled(false);

        txt_izin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_izin.setEnabled(false);

        txt_sakit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_sakit.setEnabled(false);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("hari");

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("hari");

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("hari");

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("hari");

        txt_alfa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_alfa.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbox_alfa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_sakit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_izin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel10))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(cbox_cuti, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_sakit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txt_izin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txt_cuti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_alfa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_cuti)
                    .addComponent(txt_cuti, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_izin)
                    .addComponent(txt_izin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_sakit)
                    .addComponent(txt_sakit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_alfa)
                    .addComponent(jLabel12)
                    .addComponent(txt_alfa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        Lembur.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lembur.setText("Jam Lembur");

        cbox_lembur.setBackground(new java.awt.Color(204, 204, 204));
        cbox_lembur.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbox_lembur.setText("Lembur");
        cbox_lembur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_lemburItemStateChanged(evt);
            }
        });

        txt_lembur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_lembur.setEnabled(false);

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("jam");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lembur)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(cbox_lembur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_lembur, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel14)
                .addGap(42, 42, 42))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lembur)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_lembur)
                    .addComponent(txt_lembur, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txt_slip.setColumns(20);
        txt_slip.setRows(5);
        jScrollPane2.setViewportView(txt_slip);

        but_bayar_gaji.setBackground(new java.awt.Color(102, 153, 255));
        but_bayar_gaji.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_bayar_gaji.setText("Bayar");
        but_bayar_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_bayar_gajiActionPerformed(evt);
            }
        });

        btn_cetak.setBackground(new java.awt.Color(153, 153, 255));
        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_print_25px.png"))); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_pilih_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(but_bayar_gaji)))
                .addGap(102, 102, 102)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cetak)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cetak)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cb_pilih_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(but_bayar_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_gajiLayout = new javax.swing.GroupLayout(panel_gaji);
        panel_gaji.setLayout(panel_gajiLayout);
        panel_gajiLayout.setHorizontalGroup(
            panel_gajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gajiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_gajiLayout.setVerticalGroup(
            panel_gajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gajiLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_menu.addTab("tab3", panel_gaji);

        bg_main.add(main_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 1080, 630));

        jPanel8.setBackground(new java.awt.Color(122, 72, 221));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        bg_main.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 710, 1110, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bg_mainFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bg_mainFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mainFocusLost

    private void but_menu_karyawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_menu_karyawanMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_menu_karyawanMousePressed

    private void but_menu_gajiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_menu_gajiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_menu_gajiMousePressed

    private void bg_mainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mainMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_bg_mainMouseDragged

    private void label_daftar_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_daftar_karyawanMouseClicked
        // TODO add your handling code here:
         this.tampil_tabel();
     
//  Masuk Menu List Data Karwayan
        main_menu.setSelectedIndex(0);
    }//GEN-LAST:event_label_daftar_karyawanMouseClicked

    private void label_bayar_gajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_bayar_gajiMouseClicked
        // TODO add your handling code here:
//  Masuk Menu Penggajian
        main_menu.setSelectedIndex(2);
        cbox_cuti.setSelected(false);
        cbox_izin.setSelected(false);
        cbox_sakit.setSelected(false);
        cbox_alfa.setSelected(false);
        cbox_lembur.setSelected(false);
        txt_cuti.setText("");
        txt_izin.setText("");
        txt_sakit.setText("");
        txt_alfa.setText("");
        txt_lembur.setText("");
        txt_slip.setText("");
        txt_slip.setFocusable(false);
        txt_slip.setEnabled(true);
        cb_pilih_nama.removeAllItems();
        cb_pilih_nama.setSelectedIndex(-1);
        
        try {
            rst = stm.executeQuery("select nama from karyawan");
            while(rst.next()){
                String nama = rst.getString("nama");
                cb_pilih_nama.addItem(nama);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_label_bayar_gajiMouseClicked

    private void btn_insert_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insert_dataActionPerformed
        // TODO add your handling code here:
        
        String ins_nama=this.getNama();
        String ins_pendidikan=this.pilih_pendidikan();
        String ins_kelamin=this.pilih_kelamin();
        String ins_sisa_cuti=String.valueOf(this.sisa_cuti());
        String ins_tanggal=this.getTanggal();
        db.insert_data(ins_nama, ins_pendidikan, ins_kelamin, ins_sisa_cuti, ins_tanggal);
        main_menu.setSelectedIndex(2);
        this.tampil_tabel();
    }//GEN-LAST:event_btn_insert_dataActionPerformed

    private void but_bayar_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_bayar_gajiActionPerformed
        // TODO add your handling code here:
        
        txt_slip.setText("");
        
        tanggal tgl = new tanggal();
        hitung_gaji gaji = new hitung_gaji();
        
        try {
            gaji.cuti = Integer.valueOf(txt_cuti.getText());
        }
        catch(NumberFormatException e) {
        }
        
        try {
            gaji.sakit = Integer.valueOf(txt_sakit.getText());
        }
        catch(NumberFormatException e) {
        }
        
        try {
            gaji.izin = Integer.valueOf(txt_izin.getText());
        }
        catch(NumberFormatException e) {
        }
       
        try {
            gaji.alfa = Integer.valueOf(txt_alfa.getText());
        }
        catch(NumberFormatException e) {
        }
        
        try {
            gaji.lembur = Integer.valueOf(txt_lembur.getText());
        }
        catch(NumberFormatException e) {
        }
        
//  Ambil data dari database
        db.select_user(String.valueOf(cb_pilih_nama.getSelectedItem()));
       
//  Cetak de txt_slip
        try {
            if (tgl.hitung_tanggal_gajian(db.getUser_tanggal()) > 15 ){              
                txt_slip.setText("============  Slip Gaji Karyawan PT Sumber Rejeki  ============"+ "\n\n" +
                "Nama Karyawan       : " + cb_pilih_nama.getSelectedItem() + "\n" +
                "Pendidikan Terakhir : " + db.getUser_pendidikan() + "\n" +
                "Kelamin             : " + db.getUser_kelamin() + "\n" +
                "Tanggal             : " + db.getUser_tanggal() + "\n" +
                "________________________________________________________" + "\n\n"+
                "Gaji Pokok : Rp. " + Integer.toString(gaji.tunjangan_gaji(db.getUser_pendidikan())) + "\n\n" +
                "Lembur     : Rp. " + String.valueOf(gaji.tunjangan_lembur()) + "\n\n" +
                "Jumlah Potongan \n" +
                "Cuti     : Rp. " + String.valueOf(gaji.pot_cuti(Integer.valueOf(db.getUser_cuti()))) + "\n" +
                "Izin     : Rp. " + String.valueOf(gaji.pot_izin()) + "\n" +
                "Sakit    : Rp. " + String.valueOf(gaji.pot_sakit()) + "\n" +
                "Alfa     : Rp. " + String.valueOf(gaji.pot_alfa()) + "\n" +
                "Total Potongan : Rp. " + String.valueOf(gaji.total_potongan()) + "\n\n\n" +
                "Total Gaji yang Diterima : Rp. " + gaji.total_gaji_diterima()                      
                );             
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Gaji "+db.getUser_nama()+ " Bulan Ini Sudah Dibagikan");
            }
        } catch (ParseException ex) {
            Logger.getLogger(Home_UI.class.getName()).log(Level.SEVERE, null, ex);
          Logger.getLogger(Home_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_but_bayar_gajiActionPerformed

    private void btn_tambah_data_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_data_baruActionPerformed
        // TODO add your handling code here:

        //  Masuk Menu Tambah Data Karyawan
        main_menu.setSelectedIndex(1);
        txt_insert_nama.setText("");
        txt_insert_tanggal.setText("");
        btGroup_Pendidikan.clearSelection();
        btGroup_Kelamin.clearSelection();
    }//GEN-LAST:event_btn_tambah_data_baruActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:

        //  Pilih Row yang di klik
        int x = jTable1.getSelectedRow();
        String del_nama = String.valueOf(jTable1.getValueAt(x, NORMAL));
        db.delete_data(del_nama);
        this.tampil_tabel();

    }//GEN-LAST:event_button_deleteActionPerformed

    private void label_daftar_karyawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_daftar_karyawanMouseEntered
        // TODO add your handling code here:
        but_menu_karyawan.setBackground(new Color (64,43,100));
    }//GEN-LAST:event_label_daftar_karyawanMouseEntered

    private void label_daftar_karyawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_daftar_karyawanMouseExited
        // TODO add your handling code here:
        but_menu_karyawan.setBackground(new Color (85,98,215));
    }//GEN-LAST:event_label_daftar_karyawanMouseExited

    private void label_bayar_gajiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_bayar_gajiMouseEntered
        // TODO add your handling code here:
        but_menu_gaji.setBackground(new Color (64,43,100));
    }//GEN-LAST:event_label_bayar_gajiMouseEntered

    private void label_bayar_gajiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_bayar_gajiMouseExited
        // TODO add your handling code here:
        but_menu_gaji.setBackground(new Color (85,98,215));
    }//GEN-LAST:event_label_bayar_gajiMouseExited

    private void cbox_cutiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_cutiItemStateChanged
        // TODO add your handling code here:
        if (cbox_cuti.isSelected()){
            txt_cuti.setEnabled(true);
        }
        else {
            txt_cuti.setText(null);
            txt_cuti.setEnabled(false);
        }
    }//GEN-LAST:event_cbox_cutiItemStateChanged

    private void cbox_izinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_izinItemStateChanged
        // TODO add your handling code here:
        if (cbox_izin.isSelected()){
            txt_izin.setEnabled(true);
        }
        else {
            txt_izin.setText(null);
            txt_izin.setEnabled(false);
        }
    }//GEN-LAST:event_cbox_izinItemStateChanged

    private void cbox_sakitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_sakitItemStateChanged
        // TODO add your handling code here:
        if (cbox_sakit.isSelected()){
            txt_sakit.setEnabled(true);
        }
        else {
            txt_sakit.setText(null);
            txt_sakit.setEnabled(false);
        }
    }//GEN-LAST:event_cbox_sakitItemStateChanged

    private void cbox_alfaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_alfaItemStateChanged
        // TODO add your handling code here:
        if (cbox_alfa.isSelected()){
            txt_alfa.setEnabled(true);
        }
        else {
            txt_alfa.setText(null);
            txt_alfa.setEnabled(false);
        }
    }//GEN-LAST:event_cbox_alfaItemStateChanged

    private void cbox_lemburItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_lemburItemStateChanged
        // TODO add your handling code here:
        if (cbox_lembur.isSelected()){
            txt_lembur.setEnabled(true);
        }
        else {
            txt_lembur.setText(null);
            txt_lembur.setEnabled(false);
        }
    }//GEN-LAST:event_cbox_lemburItemStateChanged

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
//  Menyimpan Slip Gaji ke file .txt
        PrintWriter out = null;
        try {
            // TODO add your handling code here:
            out = new PrintWriter(new BufferedWriter(new FileWriter(new File("slip_gaji",String.valueOf(cb_pilih_nama.getSelectedItem())+".txt"))));
            out.write(txt_slip.getText());
            out.close();
            
            
//  Membuka Notepad dan open file berdasarkan nama
            String dir = String.valueOf(cb_pilih_nama.getSelectedItem()+".txt");
            ProcessBuilder pb = new ProcessBuilder("Notepad.exe", "slip_gaji/" +dir);
            pb.start();
                 
        } catch (IOException ex) {
            Logger.getLogger(Home_UI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            out.close();
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home_UI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lembur;
    private javax.swing.JPanel bg_main;
    private javax.swing.ButtonGroup btGroup_Kelamin;
    private javax.swing.ButtonGroup btGroup_Pendidikan;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_insert_data;
    private javax.swing.JToggleButton btn_tambah_data_baru;
    private javax.swing.JButton but_bayar_gaji;
    private javax.swing.JPanel but_menu_gaji;
    private javax.swing.JPanel but_menu_karyawan;
    private javax.swing.JButton button_delete;
    private javax.swing.JComboBox<String> cb_pilih_nama;
    private javax.swing.JCheckBox cbox_alfa;
    private javax.swing.JCheckBox cbox_cuti;
    private javax.swing.JCheckBox cbox_izin;
    private javax.swing.JCheckBox cbox_lembur;
    private javax.swing.JCheckBox cbox_sakit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_bayar_gaji;
    private javax.swing.JLabel label_daftar_karyawan;
    private javax.swing.JTabbedPane main_menu;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panel_daftar_karyawan;
    private javax.swing.JPanel panel_gaji;
    private javax.swing.JPanel panel_input_karyawan;
    private javax.swing.JRadioButton pend_d3;
    private javax.swing.JRadioButton pend_s1;
    private javax.swing.JRadioButton pend_sma;
    private javax.swing.JRadioButton rad_laki_laki;
    private javax.swing.JRadioButton rad_perempuan;
    private javax.swing.JTextField txt_alfa;
    private javax.swing.JTextField txt_cuti;
    private javax.swing.JTextField txt_insert_nama;
    private javax.swing.JTextField txt_insert_tanggal;
    private javax.swing.JTextField txt_izin;
    private javax.swing.JTextField txt_lembur;
    private javax.swing.JTextField txt_sakit;
    private javax.swing.JTextArea txt_slip;
    // End of variables declaration//GEN-END:variables
}
